name: Tests

on: ['push']

jobs:
  test1:
    name: Test push from docker hub to ghcr
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup bats
        uses: bats-core/bats-action@2.1.0
        with:
          bats-version: 1.9.0
          support-install: false
          assert-install: false
          detik-install: false
          file-install: false