name: Tests

on: ['push']

jobs:
  test1:
    name: Test push from docker hub to ghcr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install required packages
        run: |
          echo {{ runner.os }}
          echo {{ runner.arch }}
          echo {{ runner.platform }}
          echo {{ runner.osversion }}