name: Tests

on: ['pull_request']

jobs:
  test1:
    name: Test push from docker hub to ghcr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get image tag from commit hash
        run: |
          SHORT_HASH=$(git rev-parse --short "$GITHUB_SHA")
          echo "TAG=${SHORT_HASH}" >> $GITHUB_ENV

      - name: Login ghcr
        uses: docker/login-action@v1
        with:
          registry: 'ghcr.io'
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Test retag and pushing single destination image
        uses: akhilerm/tag-push-action@experiment
        with:
          src: docker.io/openebs/linux-utils:ci
          dst: |
            ghcr.io/akhilerm/linux-utils:${{ env.TAG }}
      
      - name: Test retag and pushing multiple destination image
        uses: akhilerm/tag-push-action@experiment
        with:
          src: docker.io/openebs/linux-utils:ci
          dst: |
            ghcr.io/akhilerm/linux-utils:${{ env.TAG }}-test1
            ghcr.io/akhilerm/linux-utils:latest
            ghcr.io/akhilerm/linux-utils:ci
      
      - name: Test retag and pushing image
        uses: akhilerm/tag-push-action@experiment
        with:
          src: ghcr.io/openebs/linux-utils:ci
          dst: |
            docker.io/akhilerm/linux-utils:${{ env.TAG }}
